version: '3'
services:
  svisit2:
    build:
      context: ./svisit2
      dockerfile: Dockerfile
    privileged: true
    volumes:
      - svdata:/svisit
    networks:
      - svisit-network
    ports:
      - "0.0.0.0:8888:8888"
      - "0.0.0.0:8080:8080"
      - "0.0.0.0:8443:8443"

  backend-web:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DB_SCHEMA=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=backend-db
    depends_on:
      - backend-db
    ports:
      - "0.0.0.0:5000:3000"
    networks:
      - svisit-network
      - backend-network

  backend-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    ports:
      - "0.0.0.0:5432:5432"
    networks:
      - backend-network

volumes:
  dbdata:
  svdata:

networks:
  svisit-network:
    driver: bridge
  backend-network:
    driver: bridge
