version: '3'
services:
  svisit2:
    privileged: true
#    pid: host
#    cgroup: host
    build:
      context: ./svisit2
      dockerfile: Dockerfile
    volumes:
      - svhome:/svisit
      - svdb:/usr/local/svisit
      - /usr/share/zoneinfo/Asia/Tokyo:/etc/localtime
    networks:
      - svisit-network
    hostname: svisit2
    ports:
      - "0.0.0.0:8888:8888"
      - "0.0.0.0:8080:8080"
      - "0.0.0.0:8443:8443"

  backend-web:
    build: 
#      context: ./backend/demo-httpheader
      context: ./backend/the-internet
      dockerfile: Dockerfile
    volumes:
      - /usr/share/zoneinfo/Asia/Tokyo:/etc/localtime
    environment:
      - PORT=3000
#      - DB_SCHEMA=postgres
#      - DB_USER=postgres
#      - DB_PASSWORD=postgres
#      - DB_HOST=backend-db
#    depends_on:
#      - backend-db
    ports:
      - "0.0.0.0:5000:3000"
    networks:
      - svisit-network
      - backend-network
    hostname: backend-web
#  backend-db:
#    image: postgres:latest
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    volumes:
#      - "dbdata:/var/lib/postgresql/data"
#      - /usr/share/zoneinfo/Asia/Tokyo:/etc/localtime
#    ports:
#      - "0.0.0.0:5432:5432"
#    networks:
#      - backend-network

volumes:
#  dbdata:
  svhome:
  svdb:

networks:
  svisit-network:
    driver: bridge
  backend-network:
    driver: bridge
