/'
https://www.plantuml.com/plantuml/uml/
'/
@startuml
participant ”ブラウザ” as browser order 10
participant nginx order 20
participant svisitd order 30
participant backend order 40
group "認証不要なURL”
  browser -> nginx: request
  rnote over nginx
    backendへ振り分け
  endrnote
  nginx -> backend: 
  activate backend
  backend -> nginx
  deactivate backend
  nginx -> browser:response
end
group "認証必要なURL”
  browser -> nginx: request
  rnote over nginx:svisitdへ振り分け
  nginx -> svisitd: 
  activate svisitd 
  rnote over svisitd:セッション有効性の判断
  group "認証済み”
    svisitd -> backend:元request 
    activate backend
    backend -> svisitd
    deactivate backend
    svisitd -> nginx
    nginx -> browser:response
  end
  group "未認証”
    svisitd -> nginx:認証画面等
    nginx -> browser:認証画面等
    browser -> nginx:UserID,Token等
    rnote over nginx:svisitdへ振り分け
    nginx -> svisitd
    rnote over svisitd:認証処理
    / note over backend #FFAAAA:requestが/system/の場合、\nここで上書き問題が発生
    group "認証失敗"
      svisitd -> nginx:エラー画面等
      nginx -> browser:エラー画面等
    end
    group "認証成功"
      svisitd -> backend:元request
      activate backend
      backend -> svisitd
      deactivate backend
      svisitd -> nginx
      deactivate svisitd
      nginx -> browser:response
    end
  end
end
group "/system/*”
  browser -> nginx: request
  rnote over nginx:svisitdへ振り分け
  nginx -> svisitd: 
  rnote over svisitd:systemコンテンツ出力
  svisitd -> nginx
  nginx -> browser:systemコンテンツ
end
@enduml
