@startuml
skinparam BackgroundColor transparent
skinparam componentStyle rectangle
package "クライアント側" as client {
     [ブラウザ] as browser
     [Token監視プロセス] as token
}

package "サーバー側" as server {
   node Backend {
     [backend]
     note bottom of backend
       業務Webアプリケーション
     end note
   }
   node SecureVisit {
     [svisitd]
     note bottom of svisitd
       認証処理
     end note
     [nginx]
     note bottom of nginx
       振分処理等
     end note
   }
}
[browser] <-> [SecureVisit]
@enduml
